name: farma_auth
description: "An app to authenticate users."
publish_to: 'none'
version: 1.13.00

environment:
  sdk: ^3.8.1

dependencies:
  android_id: ^0.4.0
  device_info_plus: ^12.1.0
  flutter:
    sdk: flutter  
  http: ^1.5.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  window_manager: ^0.5.1
  tray_manager: ^0.5.1
  window_size: ^0.1.0
  local_notifier: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - windows/runner/resources/tray_icon.ico
    - windows/runner/resources/app_icon.ico
